#!/usr/bin/env bash
set -e
[ -z "$npm_execpath" ] && exit 1;

werk build
npm test

source .creds-aws

terraform -chdir=terraform init
terraform -chdir=terraform apply

CLOUDFRONT_DISTRIBUTION_ID=$(terraform -chdir=terraform output -raw cloudfront_distribution_id)

aws s3 sync s3://cloudfront-src-garden-homepage/primary s3://cloudfront-src-garden-homepage/secondary
aws s3 sync --delete packages/app/dist s3://cloudfront-src-garden-homepage/primary
aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/index.html" >/dev/null
